apiVersion: apps/v1
kind: Deployment
metadata:
  name: selected-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        my-awesome-label: "true"
      containers:
        - name: nginx
          image: nginx:latest
